services:
  - type: web
    name: mohit-ai-backend
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mohit-ai-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: LOG_LEVEL
        value: info
      - key: FRONTEND_URL
        value: https://mohit-ai-frontend.onrender.com
      # Add these manually in Render dashboard for security:
      # - TWILIO_ACCOUNT_SID
      # - TWILIO_AUTH_TOKEN
      # - TWILIO_PHONE_NUMBER
      # - ELEVENLABS_API_KEY
      # - OPENAI_API_KEY or GOOGLE_AI_API_KEY
      # - SENDGRID_API_KEY or SMTP credentials

databases:
  - name: mohit-ai-db
    databaseName: mohit_ai
    user: mohit_ai_user
    plan: free
    postgresMajorVersion: 15